import{a as v,S as P,i as s}from"./assets/vendor-5YrzWRhu.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&c(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function c(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();const q="51722729-ee26f011f433678f7a46d3d5a",R="https://pixabay.com/api/",$=15;async function f(r,o=1){try{return(await v.get(R,{params:{key:q,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:$}})).data}catch(n){throw n}}const p=document.querySelector(".gallery"),h=document.querySelector(".loader"),m=document.querySelector(".load-more"),B=new P(".gallery a",{captionsData:"alt",captionDelay:250});function y(r){const o=r.map(({webformatURL:n,largeImageURL:c,tags:e,likes:t,views:i,comments:S,downloads:E})=>`
    <li class="gallery-item">
      <a href="${c}">
        <img src="${n}" alt="${e}" loading="lazy" />
      </a>
      <div class="info">
        <p><b>Likes:</b> ${t}</p>
        <p><b>Views:</b> ${i}</p>
        <p><b>Comments:</b> ${S}</p>
        <p><b>Downloads:</b> ${E}</p>
      </div>
    </li>`).join("");p.insertAdjacentHTML("beforeend",o),B.refresh()}function M(){p.innerHTML=""}function g(){h.classList.remove("loader-hidden")}function d(){h.classList.add("loader-hidden")}function O(){m.classList.remove("hidden")}function L(){m.classList.add("hidden")}const u=document.querySelector(".form"),A=u.querySelector('input[name="search-text"]');let l="",a=1,b=0;const _=15;u.addEventListener("submit",x);document.querySelector(".load-more").addEventListener("click",H);async function x(r){if(r.preventDefault(),l=A.value.trim(),!l){s.error({title:"Error",message:"Search query cannot be empty",position:"topRight"});return}a=1,M(),L(),g();try{const o=await f(l,a);if(d(),o.hits.length===0){s.info({title:"Info",message:"No images found. Please try another search.",position:"topRight"});return}b=o.totalHits,y(o.hits),w(),u.reset()}catch{d(),s.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}}async function H(){a+=1,g();try{const r=await f(l,a);d(),y(r.hits),w(),C()}catch{d(),s.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}}function w(){a*_>=b?(L(),s.info({title:"End",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):O()}function C(){const{height:r}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
